version: '3'

services:
  nginx:
    build:
     context: .
     dockerfile: ./modules/nginx-ssl/Dockerfile
    ports:
      - "443:443"

  uwsgi:
    build:
     context: .
     dockerfile: ./modules/uwsgi-flask/Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./modules/uwsgi-flask/app:/var/www/app
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - PEPPER=$PEPPER
      - APP_SECRET=$APP_SECRET

  mariadb:
    image: mariadb
    logging:
      driver: none
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD